[tool.ruff]
builtins = ["_"]
line-length = 400
select = ["E","F","W"]
ignore = [
	"W191"   # Indentation contains tabs
]

[tool.isort]
profile = "black"
line_length = 1000
force_sort_within_sections = true
combine_as_imports = true
lines_between_types = 1
include_trailing_comma = true
multi_line_output = 3
force_single_line = false
default_section = "THIRDPARTY"
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_third_party = ["Components", "Screens", "Tools"]
known_first_party = ["Plugins"]
no_lines_before = ["STDLIB"]
order_by_type = false
