name: build

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Build python 3.12
        run: |
          pip3 install Cheetah3
          python -m compileall -l . -r 10 -q
          cheetah compile -R plugin
          python testsuite/evil_eval.py

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build python 3.11
        run: |
          pip3 install Cheetah3
          python -m compileall -l . -r 10 -q
          cheetah compile -R plugin
          python testsuite/evil_eval.py

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Build python 3.10
        run: |
          pip3 install Cheetah3
          python -m compileall -l . -r 10 -q
          cheetah compile -R plugin
          python testsuite/evil_eval.py

      - uses: actions/checkout@v4
        with:
          ref: 'main'
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Build python 3.9
        run: |
          sudo apt-get -q update
          sudo apt-get install -y closure-compiler nodejs npm dos2unix gettext python3-sphinx
          sudo npm install -g jshint
          pip3 install Cheetah3
          pip3 install autopep8
          pip3 install pyOpenSSL
          pip3 install twisted
          pip3 install sphinx-rtd-theme
          pip3 install sphinxcontrib-napoleon
          pip3 install sphinxcontrib-websupport
          pip3 install sphinxcontrib-httpdomain
          python -m compileall -l . -r 10 -q
          cheetah compile -R plugin
          python testsuite/evil_eval.py
          ./CI/build.sh

          ./CI/create_ipk.sh
          export PKG1=$(ls -1 *_all.ipk)
          mkdir Rel
          touch ./Rel/.nojekyll
          mv "${PKG1}" ./Rel
          cd Rel
          export PKG1=$(ls -1 *_all.ipk)
          ln -s "${PKG1}" enigma2-plugin-extensions-openwebif_latest_all.ipk
          cd ..
          cd doc
          make html
          cd build/html
          mv * ../../../Rel/
          cd ../../../

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Rel
          force_orphan: true
